### ISSUE TITLE
Mobile version peer code reviews

### ISSUE THREAD

**Issue by norbiboy1** [norbiboy1/Portfolio#5]

**Comment by tusinahmed** [comment]
@norbiboy1  Your project looks fine. you worked hard and it's fantastic. But I think in the CSS part you can add box-sizing.  border-box

**Comment by siddghosh108** [comment]
@norbiboy1, I went through your HTML and CSS script and everuthing seems tobe fine, butjust a small suggestion from myend is that after the header section you could have used the <main section

**Comment by norbiboy1** [comment]
😃 
Thank you very much, so I will change it for a better design.
👍 Thank you for the suggestions
